language: node_js
node_js:
  - "6"
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
    - packages/whosmysanta-core
before_install:
  - time npm i -g lerna@prerelease yarn --cache-min 999999999
install:
  - time lerna exec -- yarn
script:
  - yarn run lint
  - yarn run flow
  - yarn run test
