language: node_js
node_js:
  - "6"
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
    - packages/whosmysanta-core
before_install:
  - time npm i -g yarn --cache-min 999999999
install:
  - time yarn
  - lerna bootstrap
script:
  - lerna run lint
  - lerna run flow
  - lerna run test
